name: Claybook
options:
  bundleIdPrefix: com.claybook
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: 1
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UIRequiresFullScreen: true
    INFOPLIST_KEY_NSCameraUsageDescription: "Claybook uses the camera to photograph your pottery pieces at each stage."
    INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Claybook accesses your photo library to add photos of your pottery pieces."
    INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO

targets:
  Claybook:
    type: application
    platform: iOS
    sources:
      - path: Claybook
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.claybook.app
        INFOPLIST_KEY_CFBundleDisplayName: Claybook
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
  ClaybookTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ClaybookTests
    dependencies:
      - target: Claybook
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Claybook.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Claybook"
        BUNDLE_LOADER: "$(TEST_HOST)"
